#include<iostream>
using namespace std;
enum TokenType {
	BEGIN_SY, PROGRAM, IS, END_SY, PROC_SY, INTEGER_SY, COLON_SY, ID_SY, ENDWHILE, CALL, BOOLEAN_SY, Lthan_sy, SEMICOLON_SY, COMMA_SY, READ_SY, WRITE_SY, IF_SY,
	THEN_SY, ENDIF_SY, ELSE_SY, WHILE_SY, DO_SY, ENDWHILE_SY, CALL_SY, LPAREN_SY, RPAREN_SY, OR_SY, AND_SY, NOT_SY,
	MINUS_SY, GTHAN_SY, LTHAN_SY, NUMBER_SY, GOE_SY, LOE_SY, NOTEQUAL_SY, EQUAL_SY, PLUS_SY, MULTI_SY, DIV_SY, NUMBER,
	COMMENT_SY, MULTICOMMENT_SY, EOF_SY, ERROR_SY,STOP,ELSEIF,LEFTPARANT,RIGHTPARANT,AHMED, EQUALLL_SY
};
struct Token
{ 
	string tname;
	TokenType ttype;
	Token();
	string getTokenType();
};

